name: Build Android Release

on:
  workflow_dispatch:  # 这允许手动触发工作流
    inputs:
      build-type:
        description: 'Build type (apk or appbundle)'
        required: true
        default: 'apk'
        type: choice
        options:
        - apk
        - appbundle
      branch:
        description: 'Branch to build from'
        required: true
        default: 'main'
        type: choice
        options:
          - main
      flavor:
        description: 'Product flavor (optional)'
        required: false
        type: string
      distribute-to-firebase:
        description: 'Distribute to firebase (optional)'
        required: true
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch || 'main' }}  # 使用输入的分支或默认main分支
      
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Set up Keystore
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" > project-led-release-key.jks
        base64 -d project-led-release-key.jks > android/app/project-led-release-key.jks
        rm project-led-release-key.jks

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.3'  # 使用你项目所需的Flutter版本
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build APK or App Bundle
      run: |
        if [ "${{ github.event.inputs.build-type }}" == "appbundle" ]; then
          flutter build appbundle --release
        else
          flutter build apk --release
        fi
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-build
        path: |
          build/app/outputs/flutter-apk/app-release.apk
          build/app/outputs/bundle/release/app-release.aab
        if-no-files-found: warn

    - name: Distribute Preparation
      id: distribute
      run: |
        if [ -f build/app/outputs/bundle/release/app-release.aab ]; then
          echo "file=build/app/outputs/bundle/release/app-release.aab" >> $GITHUB_OUTPUT
        elif [ -f build/app/outputs/flutter-apk/app-release.apk ]; then
          echo "file=build/app/outputs/flutter-apk/app-release.apk" >> $GITHUB_OUTPUT
        else
          echo "Error: No release file found!"
          exit 1
        fi
    
    - name: Distribute to Firebase
      if: ${{ github.event.inputs.distribute-to-firebase }} == true
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }} # 你的Firebase应用ID
        token: ${{ secrets.FIREBASE_TOKEN }} # 之前获取的Firebase token
        groups: StrikingLED # 分发组，可以是多个组用逗号分隔
        file: ${{ steps.distribute.outputs.file }}
        releaseNotes: "Build #${{ github.run_number }} - ${{ github.sha }}"
